### ISSUE TITLE
Changes diff recreates all sub resources outputing unreadable diff

### ISSUE THREAD

**Issue by maciejdudzinski** [fastly/terraform-provider-fastly#104]
Adding new subresources or changing existing one results in removal and recreation of all subresources of given type. It affects backends, headers, conditions, request_settings, ...

Is it known behavior or a bug? Can it be fixed?

### Terraform Version
```
Terraform v0.11.10
+ provider.fastly v0.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

### Terraform Configuration Files
```hcl
provider "fastly" {
  api_key = "${var.api_key}"
}


resource "fastly_service_v1" "demo" {
  name = "my-unique-example-demofastly"

  domain {
    name    = "my-unique-example-domain.com"
    comment = "demo"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  force_destroy = true
}
```

### Expected Behavior
Adding another subresource:
```hcl
  backend {
    address = "127.0.0.2"
    name    = "localhost2"
    port    = 80
  }
```
Should produce diff only containing addition of new backend.

### Actual Behavior
All backends are removed and recreated in diff making one line changes completely obscured.
```
  ~ fastly_service_v1.demo
      backend.#:                                "1" => "2"
      backend.2826743015.address:               "127.0.0.1" => "127.0.0.1"
      backend.2826743015.auto_loadbalance:      "true" => "true"
      backend.2826743015.between_bytes_timeout: "10000" => "10000"
      backend.2826743015.connect_timeout:       "1000" => "1000"
      backend.2826743015.error_threshold:       "0" => "0"
      backend.2826743015.first_byte_timeout:    "15000" => "15000"
      backend.2826743015.healthcheck:           "" => ""
      backend.2826743015.max_conn:              "200" => "200"
      backend.2826743015.max_tls_version:       "" => ""
      backend.2826743015.min_tls_version:       "" => ""
      backend.2826743015.name:                  "localhost" => "localhost"
      backend.2826743015.port:                  "80" => "80"
      backend.2826743015.request_condition:     "" => ""
      backend.2826743015.shield:                "" => ""
      backend.2826743015.ssl_ca_cert:           "" => ""
      backend.2826743015.ssl_cert_hostname:     "" => ""
      backend.2826743015.ssl_check_cert:        "true" => "true"
      backend.2826743015.ssl_ciphers:           "" => ""
      backend.2826743015.ssl_client_cert:       <sensitive> => <sensitive> (attribute changed)
      backend.2826743015.ssl_client_key:        <sensitive> => <sensitive> (attribute changed)
      backend.2826743015.ssl_hostname:          "" => ""
      backend.2826743015.ssl_sni_hostname:      "" => ""
      backend.2826743015.use_ssl:               "false" => "false"
      backend.2826743015.weight:                "100" => "100"
      backend.4157781680.address:               "" => "127.0.0.2"
      backend.4157781680.auto_loadbalance:      "" => "true"
      backend.4157781680.between_bytes_timeout: "" => "10000"
      backend.4157781680.connect_timeout:       "" => "1000"
      backend.4157781680.error_threshold:       "" => "0"
      backend.4157781680.first_byte_timeout:    "" => "15000"
      backend.4157781680.healthcheck:           "" => ""
      backend.4157781680.max_conn:              "" => "200"
      backend.4157781680.max_tls_version:       "" => ""
      backend.4157781680.min_tls_version:       "" => ""
      backend.4157781680.name:                  "" => "localhost2"
      backend.4157781680.port:                  "" => "80"
      backend.4157781680.request_condition:     "" => ""
      backend.4157781680.shield:                "" => ""
      backend.4157781680.ssl_ca_cert:           "" => ""
      backend.4157781680.ssl_cert_hostname:     "" => ""
      backend.4157781680.ssl_check_cert:        "" => "true"
      backend.4157781680.ssl_ciphers:           "" => ""
      backend.4157781680.ssl_client_cert:       <sensitive> => <sensitive> (attribute changed)
      backend.4157781680.ssl_client_key:        <sensitive> => <sensitive> (attribute changed)
      backend.4157781680.ssl_hostname:          "" => ""
      backend.4157781680.ssl_sni_hostname:      "" => ""
      backend.4157781680.use_ssl:               "" => "false"
      backend.4157781680.weight:                "" => "100"
```

### Steps to Reproduce
1. Copy example of fastly terraform service
2. `terraform apply`
3. Add a new backend
4. `terraform plan`

**Comment by kmotrebski** [comment]
I have the same problem.

**Comment by msuterski** [comment]
This is how the provider is designed.

It's not possible to identify most of the resources provided by Fastly's API by any immutable ID. They are mostly references by name (in the URL) that is mutable (you can update the name of a resource to a new one which becomes its ID). That's why, to be "safe" and to not mange a lot of complexity, the provider defaults to `delete all` resources of a certain type and `create all` new ones when any of the objects of that subtype changes.

It is a safe operation since the new version is being activated only after all the changes (delete and create) were performed on it. Until that happens, the old version is still active and not affected. Well, except for things that are "version-less" in Fastly's world.

**Comment by philippschulte** [comment]
Hi there 👋,

The behavior of the provider cannot be easily changed. I agree that the `diff` is difficult to read and it is annoying to find resources in the list which haven't changed. However, you can identify in the `diff` output what has been changed and what's new.

There is #45 which will allow you to set `activate` to `false` in order to create only a `draft` version once it's merged. This will allow you to review and compare the changes in the Fastly app before it goes live. You then need to manually activate the version. The downside is that it will not reuse the draft version if you run `$ terraform apply` again! The provider always clones the active version to push changes to.

#45 doesn't solve this issue but as I said at the beginning the current design cannot easily be changed. Therefore, I'll close this issue as soon as #45 gets merged.
