### ISSUE TITLE
Feature Request: Print out URL of diff after `terraform apply`

### ISSUE THREAD

**Issue by marcb1** [fastly/terraform-provider-fastly#110]
Hi there,
This is a feature that I'd be willing to implement not sure if it is even possible, which is why I'm posting it here.

After a new fastly version is activated, there is a URL that shows the diff between the latest and the current activated version. URL looks like so: `https://manage.fastly.com/configure/services/[service uuid]/diff/[last activated version id],[current activated version id]`.

We have both pieces of information in the provider plugin, here: https://github.com/terraform-providers/terraform-provider-fastly/blob/08523af8d619fac0d78262411f5f7de295981c27/fastly/resource_fastly_service_v1.go#L1386
```
			newVersion, err := conn.CloneVersion(&gofastly.CloneVersionInput{
				Service: d.Id(),
				Version: latestVersion,
			})
```

I wasn't sure if it is even possible to print the diff URL from these versions after the `terraform apply` is successful. As far as I could tell, the terraform apply only allows errors to be returned from the plugin. 

Any suggestions on how to implement, or if it is even possible.

**Comment by christophermancini** [comment]
@marcb1 you might be able to accomplish this doing something like the following in your `outputs.tf` file, though I have not tested it:

```
output "diff" {
  value = "https://manage.fastly.com/configure/services/${module.my-fastly-service.service-id}/diff/${module.my-fastly-service.active_version},${module.my-fastly-service.cloned_version}"
}
```

**Comment by Integralist** [comment]
I found the example provided above needed some tweaks for it to work. I had to replace `module` with a resource, so in this case a `fastly_service_v1` resource. If you want to try this yourselves you'll also need to change `test_service` with the name you gave to the resource:

```tf
# on the initial creation of my service I don't have a `cloned_version`
# i.e. it's set to `null`
# to avoid an error trying to interpolate `null` into a string I have to use a ternary to catch it
locals {
  cloned_version = fastly_service_v1.test_service.cloned_version == true ? fastly_service_v1.test_service.cloned_version : "..."
}

output "diff" {
  value       = "https://manage.fastly.com/configure/services/.../diff/${fastly_service_v1.test_service.active_version},${local.cloned_version}"
  description = "A URL to check diff between two service versions."
}
```

So after creating the service for the first time, I see:

```
Outputs:

diff = "https://manage.fastly.com/configure/services/.../diff/1,..."
```

Now if I update the `comment` for the domain and apply that change a new version (`2`) will be activated for me with that change, and yet the output still shows:

```
Outputs:

diff = "https://manage.fastly.com/configure/services/.../diff/1,..."
```

This is confusing in the sense of the number `1` is the value extracted from the `active_version` attribute, where as I would have expected it to be `2` not `1` now.

> **NOTE**: I'm also skipping over the missing `service id` reference that's needed for the URL to be valid. Looks like the `fastly_service_v1` doesn't return any such attribute.

So this highlights to me that once the `terraform apply` is actioned, the local state isn't updated and so the user has to call either `terraform plan` or `terraform refresh` in order to update their local state file, as I demonstrate below...

```
$ terraform plan
fastly_service_v1.test_service: Refreshing state... [id=...]

...

Changes to Outputs:
  ~ diff = "https://manage.fastly.com/configure/services/.../diff/1,..." -> "https://manage.fastly.com/configure/services/.../diff/2,..."
```

In my scenario I don't have a `cloned_version` value and so it's almost like we'd need a `previously_activated_version` attribute to reference. Which is basically what the reporter of this issue is requesting.
