### ISSUE TITLE
Condition types are now uppercase

### ISSUE THREAD

**Issue by alanfriedman** [fastly/terraform-provider-fastly#148]
### Terraform Version
[0.11.7 Linux AMD 64](https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip)

### Affected Resource(s)
- condition

Fastly provider version 0.6.0
AWS provider version 2.8.0

### Actual Behavior

`condition` blocks used to accept a lowercase type (`request`, `response`, etc). Now it appears they require uppercase types (`REQUEST`, `RESPONSE`).

The lowercase types stopped working sometime after April 15th. We never bumped the major version of Terraform or the Fastly provider so did not expect a breaking change.

### Expected Behavior

I would expect the lowercase types to continue working when using the same Terraform and provider versions.

**Comment by philippschulte** [comment]
👋 I can't confirm the described behavior. You can still use lowercase values for the `type` attribute. However, by doing so the `plan` command will always detect a difference. For example `request` is not equal to `REQUEST` because the Go programming language is case sensitive and the Fastly API will always respond with an uppercase value even if the condition was created with a lowercase `type` value.

Also, both the [Fastly API](https://docs.fastly.com/api/config#api-section-condition) and the [Fastly Terraform](https://www.terraform.io/docs/providers/fastly/r/service_v1.html) docs require uppercase values for the condition `type` attribute. This hasn't changed since conditions are supported. Please have a look [here](https://github.com/terraform-providers/terraform-provider-fastly/commit/681623949e9c1300ca93a14562936f5070c785f3) in case you want to prove it yourself. The only issue I see is that the provider should throw an error if the value for the `type` attribute is not uppercase and not one of the required types.
