### ISSUE TITLE
Idempotency issue with fastly_service_v1 syslog parameter

### ISSUE THREAD

**Issue by jsierles** [fastly/terraform-provider-fastly#231]
### Terraform Version
0.12.24

### Affected Resource(s)

`fastly_service_v1.syslog`

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "service" {
  name = "${var.name}-${var.environment}"

  domain {
    name = var.domain
  }

  syslog {
    name = "LogDNA"
    address = "syslog-a.logdna.com"
    port = "12345"
    format = "%h %l %u %t \"%r\" %>s %b"
    use_tls = true
    tls_ca_cert = file("${path.module}/logdna_ca_cert.pem")
  }
}
```

### Debug Output

https://gist.github.com/jsierles/cf220a7a811dba8f41001421e00d812a

### Expected Behavior

Resource should have not required an update with no change to terraform files.

### Actual Behavior

The resource always updates in place without any changes to files.

### Steps to Reproduce

1. `terraform plan`

**Comment by ezkl** [comment]
@jsierles I'm sorry you ran into this issue.

It is likely due to our API stripping trailing whitespace when storing the value TF is reading from the PEM file. The stripped value returned by the API is what ends up in the state file, so when it gets compared to the value in the local file, it triggers the change.

Assuming this is the case, the easiest workaround is to use `trimspace` and `chomp`:
```terraform
tls_ca_cert = trimspace(chomp(file("${path.module}/logdna_ca_cert.pem")))
```

Let me know if that helps.

**Comment by jsierles** [comment]
That did the trick. Thanks!
