### ISSUE TITLE
Need separate provider for Network Config Management

### ISSUE THREAD

**Issue by anandpalanisamy** [fastly/terraform-provider-fastly#287]
Currently, Fastly configuration is managed by single terraform resource and it is creating conflict between teams.

For example, Security team manages the ACLs and related dictionaries using APIs using separate workflow and Network team is using Terraform to manage the config.  So, we need separate resources for managing those resources independently.

1. Network Config resource
2. ACL List resource
3. Dictionary resource

**Comment by phamann** [comment]
Hi @anandpalanisamy thank you for raising this issue. I believe you are also in contact with our solutions engineers about this, but i'll attempt to answer and help here too. It would be good to understand your exact problem space better, as there are already separate resources for ACL and Dictionary items which should solve your feature request to manage these feature independently. However, I have detailed some pointers below which I hope will help you with your issues and asked some questions to further understand your problem 😃. 

1) Can you clarify what you mean by "Network Config Resource" as this isn't a name i'm family with in regards to Fastly Services.
2) ACL entires can be managed as an independent resource [`fastly_service_acl_entries_v1`](https://www.terraform.io/docs/providers/fastly/r/service_acl_entries_v1.html).
3) Dictionary items can be managed as an independent resource [`fastly_service_dictionary_items_v1`](https://www.terraform.io/docs/providers/fastly/r/service_dictionary_items_v1.html). 

> For example, Security team manages the ACLs and related dictionaries using APIs using separate workflow and Network team is using Terraform to manage the config. So, we need separate resources for managing those resources independently.

Reading into this a bit more. You should be aware that Terraform won’t mutate any resources it doesn’t know about in its statefile. So you are safe to define the ACLs and related edge dictionaries that the security team uses outside of terraform completely - either via the Fastly API or UI. Which may be the best approach in this instance for your security team, rather than trying to model everything in your teams TF configuration. Alternatively, the security team could have their own TF config which only models the ACLs and Edge dictionaries.

### A couple of things to know about version-less resources (ACLs / Edge Dictionaries) that may help:

- As they are stateful, If you are going to manage the items of the ACL or Dictionary via TF, then you should only manage them via TF, otherwise any external change may get reverted the next time TF runs. What we normally recommend is using Terraform to define and assert that the the ACL/Dictionary container exists on the on the service and use the `fastly_service_acl_entries_v1` or `fastly_service_dictionary_items_v1` resource to define the initial items in that should exist within the resource. Then use TF's lifecycle `ignore_changes` field on the items resource to prevent TF from trying to manage the state after the initial apply. A more detailed example of this can be found in the documentation: https://www.terraform.io/docs/providers/fastly/r/service_dictionary_items_v1.html#supporting-api-and-ui-dictionary-updates-with-ignore_changes
- Like all resources managed by terraform; if you originally created the ACL or Dictionary via your TF config but subsequently want to want to remove the ACL or Dictionary resource from your TF config still ensuring that it exists externally (i.e. so your security team can manage independently), you need to manually remove it from the TF state. You can do this using the [`terraform state rm`](https://www.terraform.io/docs/commands/state/rm.html) command. Alternatively let TF delete the resource after removing from your config and then recreate it via the Fastly API.
- If you are using private/write-only edge dictionaries (which I think you are) you must tell Terraform that the dictionary is private via the [`write_only`](https://www.terraform.io/docs/providers/fastly/r/service_v1.html#write_only) property. Due to their write-only nature, TF will error if it attempts to read the contents of a private dictionary during a plan or apply, this property suppresses the read logic and thus the error.

---

I hope this gives you enough information to form a plan forward with your security team. As we already support everything you asked i'm going to close this issue. But feel free to comment/re-open if you have further questions.
