### ISSUE TITLE
Always invalidates and recreates Bigquery logging as long as email + secret_key are not explicitly set

### ISSUE THREAD

**Issue by qr4** [fastly/terraform-provider-fastly#314]
Terraform is updating bigquerylogging of the service every time it is run. This is fixed by explicitly setting secret_key and email on the bigquerylogging block.

```  
      + bigquerylogging {
          + dataset            = "fastly_bigquery"
          + email              = (sensitive value)
          + format             = jsonencode(
                {
                  + anomaly_score = "%{waf.anomaly_score}V"
                  + logdata       = "%{cstr_escape(waf.logdata)}V"
                  + request_id    = "%{req.http.req-id}V"
                  + rule_id       = "%{waf.rule_id}V"
                  + severity      = "%{waf.severity}V"
                  + timestamp     = "%{begin:%Y-%m-%dT%H:%M:%S}t"
                  + type          = "waf"
                  + waf_blocked   = "%{waf.blocked}V"
                  + waf_logged    = "%{waf.logged}V"
                  + waf_message   = "%{waf.message}V"
                  + waf_passed    = "%{waf.passed}V"
                }
            )
          + name               = "BigQuery WAF Logging"
          + project_id         = "my_project_id"
          + response_condition = "waf_logging_enabled"
          + secret_key         = (sensitive value)
          + table              = "waf_logs"
          + template           = "%Y%m%d"
        }
      - bigquerylogging {
          - dataset            = "fastly_bigquery" -> null
          - email              = (sensitive value)
          - format             = jsonencode(
                {
                  - anomaly_score = "%{waf.anomaly_score}V"
                  - logdata       = "%{cstr_escape(waf.logdata)}V"
                  - request_id    = "%{req.http.req-id}V"
                  - rule_id       = "%{waf.rule_id}V"
                  - severity      = "%{waf.severity}V"
                  - timestamp     = "%{begin:%Y-%m-%dT%H:%M:%S}t"
                  - type          = "waf"
                  - waf_blocked   = "%{waf.blocked}V"
                  - waf_logged    = "%{waf.logged}V"
                  - waf_message   = "%{waf.message}V"
                  - waf_passed    = "%{waf.passed}V"
                }
            ) -> null
          - name               = "BigQuery WAF Logging" -> null
          - project_id         = "my_project_id" -> null
          - response_condition = "waf_logging_enabled" -> null
          - secret_key         = (sensitive value)
          - table              = "waf_logs" -> null
          - template           = "%Y%m%d" -> null
        }
  
```

### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/fastly/fastly v0.20.1

### Affected Resource(s)
-  bigquerylogging 

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "example_service" {
...
  bigquerylogging {
    name       = "BigQuery WAF Logging"
    project_id = "my_project_id"
    dataset    = "fastly_bigquery"
    table      = "waf_logs"
    format = jsonencode({
      timestamp     = "%%{begin:%Y-%m-%dT%H:%M:%S}t",
      type          = "waf",
      request_id    = "%%{req.http.req-id}V",
      rule_id       = "%%{waf.rule_id}V",
      waf_logged    = "%%{waf.logged}V",
      waf_blocked   = "%%{waf.blocked}V",
      waf_passed    = "%%{waf.passed}V",
      severity      = "%%{waf.severity}V",
      anomaly_score = "%%{waf.anomaly_score}V",
      logdata       = "%%{cstr_escape(waf.logdata)}V",
      waf_message   = "%%{waf.message}V"
    })
    template           = "%Y%m%d"
    response_condition = "waf_logging_enabled"
  }
}
```

### Expected Behavior
The bigquerylogging resource should not have been recreated if the config didn't change.

### Actual Behavior
The bigquerylogging resource is recreated every time anew with the same config (as long as secret_key and email are not explicitly set). Setting them via a variable does not work.

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

**Comment by phamann** [comment]
Hi @qr4, thank you for submitting this issue. 

The most common reason for the behaviour you're observing is the encoding of your source data _may_ be differrent to the final value persisted by our API. 

I.e. does the variable representation of your email/secret_key contain any additional whitespace or new lines (maybe you're reading from a .google.json file or similar?). This whitespace will be removed by Fastly at the API layer and thus the clean value is persisted to the TF statefile, which in-turn will trigger a diff against your input on every apply. Hence why when you hardcode the value directly instead of passing by a variable works.

Please check your source data and let me know if this fixes it. You can use the helper functions such as `trimspace(var.secret_key)` etc to sanitise your data before passing to the field.

**Comment by qr4** [comment]
Hi @phamann,
through trial and error I could find out that the issues lies in the `secret_key` attribute.  As you suspected, this string ends on a newline (if extracted from a .google.json). Removing the trailing newline in the secret key, or calling `trimspace(...)` sadly does not resolve the issue.

Also something very peculiar happens if I have e.g. 2 ` bigquerylogging` blocks configured: one with an explicitly set `secret_key` and one extracted through other means. In this case both resources are recreated every time I do `terraform apply -auto-approve && terraform plan`. I am not sure if this is connected to the issue though.

**Comment by phamann** [comment]
@qr4 Apologies for the delay in getting back to you. We've since done some further investigation into this, as we've had a collection of similar reports to yours recently. 

It seems this is related to how Terraform encodes strings that it reads from external sources such as via `file()`,  a `data` datasource, or `TF_VAR_` environment variables. We are seeing the `\n` new line escape sequences within the private key being double encoded as `\\n` which the Fastly API then accepts and sanitises, which causes the circular plan diff. 

Therefore, can you please try our suggested workaround to see if it fixes the issue for you, which is to use `replace()` to fix the encoding:

```hcl
resource "fastly_service_v1" "example_service" {
...
  bigquerylogging {
    name         = "BigQuery WAF Logging"
    project_id   = "my_project_id"
    dataset      = "fastly_bigquery"
    table        = "waf_logs"
    secret_key   = replace(var.secret_key_source, "\\n", "\n")
...
```

> Also something very peculiar happens if I have e.g. 2 bigquerylogging blocks configured: one with an explicitly set secret_key and one extracted through other means. In this case both resources are recreated every time I do terraform apply -auto-approve && terraform plan. I am not sure if this is connected to the issue though.

This is a separate issue (which makes the diff of this issue more confusing) and is due to our use of `TypeSet` for these logging blocks and how we perform the diff of the set which causes all items to be removed and added again even if only one property changes. We intend to fix this in our next major verison release of the provider by moving the blocks to `TypeList`.

**Comment by qr4** [comment]
your suggested workaround works. thanks!

**Comment by smaeda-ks** [comment]
For those still watching this issue, we've made some changes in v0.33.0 and now return a proper error message if the `secret_key` value includes trailing space characters.

PR: https://github.com/fastly/terraform-provider-fastly/pull/439

We believe this will help users and prevent accidental logging deletion. As a reminder, we encourage you to use the `trimspace()` [function](https://www.terraform.io/docs/language/functions/trimspace.html) for this particular attribute going forward.

We appreciate your feedback. Thanks
