### ISSUE TITLE
0.28.1 is broken

### ISSUE THREAD

**Issue by yannh** [fastly/terraform-provider-fastly#395]
Hello,

And I'm sorry since this is a very vague bug report. Since 0.28.1 I am unable to apply terraform configuration that worked in the past. This report is aimed for other people hitting problems with the latest version of the Fastly provider - I suggest reverting to older versions (0.26/0.27). Unfortunately I can't provide a lot of details.

My best guess is it might be related to https://github.com/fastly/terraform-provider-fastly/commit/dda2e72c2793a7e37a46b9fc89469247ff2016f4

When a Terraform configuration is incorrect, I believe  the provider creates it, and then fails to activate it. Once the terraform configuration is fixed, I m wondering if the errors I am getting might be related to previously broken fastly service versions that were created but not activated.

### Terraform Version
0.13.6

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

### Debug Output
"Conflict" errors, that disappear when using 0.26.0 (which I reverted to)

Error: 409 - Conflict:
    Title:  Duplicate record
    Detail: Duplicate logging_syslog: 'splunk-hit'

**Comment by Integralist** [comment]
Thanks @yannh we're aware of issues with `0.28.1` and are actively investigating.

**Comment by Integralist** [comment]
@yannh we've released https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.28.2 which addresses an issue that was discovered internally but we feel it won't necessarily resolve _your_ issue because the error you see is much later in the overall logic flow than we were seeing in our error scenarios.

**To help us debug this further, can you do the following please**:

1. Upgrade to `0.28.2` and see if this resolves the issue.
2. Prefix your call to `terraform apply` with `TF_LOG=TRACE` (this will output _a lot_ of information because it will show every API request that is being made).
3. Can you share the value of `cloned_version` and `active_version` attributes in your state.

> NOTE: also keep an eye on those attributes as far as any API calls being made (e.g. what service version is being cloned and how does it align against your state values).

Thanks.

**Comment by yannh** [comment]
@Integralist Just connected the dots between you and https://www.integralist.co.uk/posts/fastly-varnish/ . I wanted to take the opportunity to thank you for this resource, it has been remarkably useful.

I *believe* the error was triggered by trying to apply a configuration that would fail to activate, leading to a version of a service that is broken & not activated - and then reverting to a known good version, which would then also fail to activate. 

If this doesn't help  - I don't think I can commit to going much deeper into this problem for now, so we could close this ticket - and I could reopen it / open a new one once I have a reproducible test case.

Thanks!

**Comment by Integralist** [comment]
re: blog post - Thanks @yannh it was only a matter of time before I joined Fastly 😀 

My hope is to improve Fastly's documentation to the point where that notorious blog post becomes redundant. 

re: this issue - yes if that's ok then please close and reopen once you're able to provide a reduced test case. 

Hopefully the 0.28.2 release helps as well.
