### ISSUE TITLE
Error: `nil` entry in `ImportState` results when importing C@E service into reusable internal TF module.

### ISSUE THREAD

**Issue by Integralist** [fastly/terraform-provider-fastly#421]
Creating this issue on behalf of a customer who reported the following to Fastly Support... 

---

I'm trying to migrate out Compute@Edge service into a reusable internal Terraform module. I'm encountering quite a few issues such as:

```
$ terraform import ...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

It also doesn't seem to recognise resources as being the same if you migrate them into a module and import from the existing service. Instead it wants to tear them all down and make new ones from scratch.

Are issues like this known about?

**Comment by Integralist** [comment]
The customer had some follow-up comments...

---

To be honest, the diff might just be misrepresenting the fact that it's just a new version being created rather than everything being torn down and recreated.

I'm using the 0.30.0 version of the provider.

Alright, I managed to address all of this. It was pretty gnarly though.

All I did was update my service to a reusable module. That was enough to confuse the Fastly provider into believing that there were actually two services with the exact same name and ID, and it offered to destroy the first one and modify the new one in-place. That's strange considering they are literally the same service.

I had to fix this by first `terraform import`ing the service and the edge dictionaries (the latter of which needed API requests to obtain their IDs, since unlike services they're not in the web UI). Then targeting was done to temporarily "fix" the duplication. Once it was reconciled with the new one, I had to use `terraform state rm` to drop the old dupes, which allowed me to `terraform apply` without targeting.

So, there's something in the fastly provider that can get confused between substantial changes, incorrectly believing a single service is actually two services. This was all the same Terraform state throughout, by the way.

**Comment by bengesoff** [comment]
So for the initial error message it sounds like maybe the service didn't exist or the ID was wrong? In this case `GetServiceDetails` would return a 404 and the `Read` function would call `d.SetId("")` without returning any error and cause the given error message. 

```go
        s, err := conn.GetServiceDetails(&gofastly.GetServiceInput{
		ID: d.Id(),
	})
	if err != nil {
		// Check if not found, if so, clear ID field and exit early.
		if e, ok := err.(*gofastly.HTTPError); ok && e.IsNotFound() {
			log.Printf("[WARN] %s for ID (%s)", fastlyNoServiceFoundErr, d.Id())
			d.SetId("")
			return nil
		}
		return diag.FromErr(err)
	}
```

The error message could actually be improved here by effectively escalating this error in the `Read` function and returning it. By returning the 404 error itself, instead of `nil`, it would be displayed instead of the ambiguous `nil entry in ImportState results` error.

I'm not quite sure about the rest of the problems in terms of the duplicate services at this point, but if there's any confusion over the ID being specified during import, that could be leading to strange diffs with services thinking they're being deleted. If it still persists after correcting the first error then maybe we should have a closer look, with some more specific examples of the `import` commands and the resource addresses.

**Comment by bengesoff** [comment]
For reference, when making the following change:

```diff
diff --git a/fastly/base_fastly_service_v1.go b/fastly/base_fastly_service_v1.go
index 3d99195e..f456000b 100644
--- a/fastly/base_fastly_service_v1.go
+++ b/fastly/base_fastly_service_v1.go
@@ -456,7 +456,7 @@ func resourceServiceRead(ctx context.Context, d *schema.ResourceData, meta inter
 		if e, ok := err.(*gofastly.HTTPError); ok && e.IsNotFound() {
 			log.Printf("[WARN] %s for ID (%s)", fastlyNoServiceFoundErr, d.Id())
 			d.SetId("")
-			return nil
+			return diag.FromErr(err)
 		}
 		return diag.FromErr(err)
 	}
```

The error message when importing with a non-existent ID goes from:
![image](https://user-images.githubusercontent.com/5968462/122030404-a545d280-cdc5-11eb-8722-fc0a5f48ec3e.png)

To:
![image](https://user-images.githubusercontent.com/5968462/122030467-b42c8500-cdc5-11eb-9622-b1eebaff9706.png)
