### ISSUE TITLE
Feature request: Add option to deactivate service as part of terraform destroy

### ISSUE THREAD

**Issue by JiriKovar** [fastly/terraform-provider-fastly#515]
### Terraform Version
1.0.11

### Affected Resource(s)
- fastly_service_v1

### Description
Currently if you have a service with active version, there are 2 options with terraform destroy:
- `force_destroy = true` which deletes the service
- `force_destroy = false` which causes the terraform to fail

We would very much need to be able to deactivate the service with destroy without causing it to fail. This is what I have expected to be a default behavior with terraform destroy being run while having `force_destroy` set to `false` and I'm sorry, but I have to ask: what even is the usecase for having it set to `false` if not deactivating the service? Deleting services that are not active, thus forcing manual deactivation beforehand? If I don't want the service to be affected by the terraform destroy command, I have better options like removing it from the state etc...

Currently the best we can do is to let the terraform destroy fail and deactivate it directly via Fastly REST API, which kind of defeats the purpose of the terraform provider.

**Comment by Integralist** [comment]
Hi @JiriKovar 

I had some spare capacity to investigate this issue and I had some follow up thoughts/comments...

The first thing I did was just go ahead and add a new `deactivate` field to the schema and setup the logic to cause the service to only be deactivated when running `terraform destroy`, and that worked fine but the big caveat for that approach was that the resource would be completely deleted from the Terraform state and so the next time you run `terraform plan` the resource would be seen as needing to be recreated and to avoid that situation would require deleting, or commenting out, the HCL configuration (which isn't a good user flow).

I then thought a bit about the situation and realised `terraform destroy` is a bad place to have the ability to deactivate a service because 'destroy' is designed to clean the destroyed resources from the state. If someone wants to deactivate a service resource, then this implies they (at some point in the future) want to restore the service. So deactivating a service should just be an UPDATE operation, which iirc is what the `activate` field should already handle.

I'm not sure what the history is behind `force_destroy` as it predates my time on the project but I imagine it was intended as a way to protect users from running `terraform destroy` on a project and not realising that a service was active (e.g. user thinks they are in a different project that only had non-service resources defined and wanted those resources destroyed).

**Comment by JiriKovar** [comment]
Hi Integralist, 

thank you for your comment. The thing is that for Fastly, spinning up a new service is an expensive operation so we were advised to reuse them via deactivation instead of deleting and creating always new ones. Which is what we are currently forced to do manually and because of the missing support for that in this terraform provider, we were also forced to abandoned running terraform destroy completely and delete / deactivate everything manually both in Azure and Fastly (we cant use `force_destroy = true` because we dont want to delete the services and we cant use `force_destroy = false` because the destroy process fails and there are no other options). And I can guarantee you that this is definitely a bad flow in comparison... 

Also from my experience, terraform destroy semantically means that you are done with the environment completely and the resources that were part of it should be released and not considered part of the environment anymore. If you run plan on a destroyed environment, you should receive a plan to create everything anew without links to any previously existing services, which is exactly what you have seen in your test. And as you know, if you want to add an existing service to an empty terraform state, you need to initialize it and import the service, which is also allowed in this case, so I believe that as far as terraform state is considered, the flow remains as designed - the deactivate flag simply means that the Fastly services should be released in a different way (leaving the deactivated service behind as compared to destroying it).

To rephrase it, because of the aforementioned constraint of not deleting services, our best achievable flow actually is:
* initialize terraform
* import existing Fastly services (that were previously deactivated by some completely different environment)
* terraform apply
* do stuff
* terraform destroy (leaving the service behind to be imported later on to a completely different environment)

Obviously, it would be the best if creating and destroying services was OK from the perspective of Fastly instead of deactivating and reusing it - that would simplify our things quite a lot. But AFAIK its not happening any time soon.

**Comment by Integralist** [comment]
Hi @JiriKovar 

Thanks for the feedback. 

I'm just experimenting a little bit with what's possible at the moment.

Thinking like a user, with the following requirements: 

- I want to create a service, with a bunch of resources.
- I want to be able to run `terraform destroy` to delete the resources while still keeping the service.
- I want to be able to import the service into another project (so the service can be reused).

So here's the changes I've made to the provider:

```diff
diff --git a/fastly/base_fastly_service.go b/fastly/base_fastly_service.go
index 2cfde578..47684793 100644
--- a/fastly/base_fastly_service.go
+++ b/fastly/base_fastly_service.go
@@ -130,6 +130,12 @@ func resourceService(serviceDef ServiceDefinition) *schema.Resource {
 				Optional:    true,
 				Description: "Services that are active cannot be destroyed. In order to destroy the Service, set `force_destroy` to `true`. Default `false`",
 			},
+
+			"reuse": {
+				Type:        schema.TypeBool,
+				Optional:    true,
+				Description: "Services that are active cannot be destroyed. This will cause the service to be deactivated allowing it to be reused by importing it into another Terraform project. Default `false`",
+			},
 		},
 	}
 
@@ -524,11 +530,10 @@ func resourceServiceDelete(_ context.Context, d *schema.ResourceData, meta inter
 	// Fastly will fail to delete any service with an Active Version.
 	// If `force_destroy` is given, we deactivate the active version and then send
 	// the DELETE call.
-	if d.Get("force_destroy").(bool) {
+	if d.Get("force_destroy").(bool) || d.Get("reuse").(bool) {
 		s, err := conn.GetServiceDetails(&gofastly.GetServiceInput{
 			ID: d.Id(),
 		})
-
 		if err != nil {
 			return diag.FromErr(err)
 		}
@@ -544,11 +549,16 @@ func resourceServiceDelete(_ context.Context, d *schema.ResourceData, meta inter
 		}
 	}
 
-	err := conn.DeleteService(&gofastly.DeleteServiceInput{
-		ID: d.Id(),
-	})
-	if err != nil {
-		return diag.FromErr(err)
+	if !d.Get("reuse").(bool) {
+		err := conn.DeleteService(&gofastly.DeleteServiceInput{
+			ID: d.Id(),
+		})
+		if err != nil {
+			return diag.FromErr(err)
+		}
+
+		d.SetId(d.Id())
+		return diag.FromErr(errors.New("don't delete the resource"))
 	}
 
 	return nil
```

The above changes let us keep the existing behaviour (e.g. you have to use `force_destroy = true` to delete the service), while adding a new `reuse` attribute to indicate that you only want to deactivate the service (when running `terraform destroy`).

Now, here's a simple Terraform project that creates a service, and a dictionary, and populates the dictionary with some items:

```hcl
terraform {
  required_providers {
    fastly = {
      source  = "fastly/fastly"
      version = "2.0.0"
    }
  }
}

variable "mydict_name" {
  type    = string
  default = "My Dictionary"
}

resource "fastly_service_vcl" "demo" {
  name = "testing-tf-deactivation"

  domain {
    name    = "testing-deactivation.integralist.co.uk"
    comment = "demo"
  }

  dictionary {
    name = var.mydict_name
  }

  reuse = true
}

resource "fastly_service_dictionary_items" "items" {
  for_each = {
    for d in fastly_service_vcl.demo.dictionary : d.name => d if d.name == var.mydict_name
  }
  service_id    = fastly_service_vcl.demo.id
  dictionary_id = each.value.dictionary_id

  items = {
    key1 : "value1"
    key2 : "value2"
  }
}
```

Once this configuration has been applied successfully and I'm ready to move on to another project I can run `terraform destroy`. Because of the use of `reuse = true` in the configuration, my hope was that the service would persist, while its nested resources would be destroyed.

The result is _partially_ correct. The service _is_ deactivated, but only the `fastly_service_dictionary_items` resource is destroyed. 

This is because all the other resources (e.g. `domain`, `dictionary`) are blocks _within_ the service (this is a bigger data modelling issue that we both are already aware of, and Fastly is aware also and is actively looking to improve the situation but realistically this isn't going to be resolved any time soon) and so those resources aren't deleted.

If I would run `terraform plan` from this current project then the plan would tell me it needs to recreate the `fastly_service_vcl` resource as well as the `fastly_service_dictionary_items` resource (which is expected as the local terraform state is now empty, due to running `terraform destroy`).

OK, so what happens if we _import_ this service into another project with the following Terraform configuration (notice I've updated the `name` attributes for the service/domain resources) and run `terraform plan`:

```hcl
terraform {
  required_providers {
    fastly = {
      source  = "fastly/fastly"
      version = "2.0.0"
    }
  }
}

resource "fastly_service_vcl" "demo" {
  name = "testing-tf-deactivation-import"

  domain {
    name    = "testing-deactivation-import.integralist.co.uk"
    comment = "demo"
  }

  reuse = true
}
```

I'll see the following plan is generated:

```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be updated in-place
  ~ resource "fastly_service_vcl" "demo" {
      + activate           = true
      ~ active_version     = 0 -> (known after apply)
      ~ cloned_version     = 1 -> (known after apply)
        id                 = "7TAuMdXDbzzRL9Sp0M8AeS"
      ~ name               = "testing-tf-deactivation" -> "testing-tf-deactivation-import"
      + reuse              = true
        # (4 unchanged attributes hidden)

      - dictionary {
          - dictionary_id = "4fgSkwtiibzepYKwVVOeBN" -> null
          - force_destroy = false -> null
          - name          = "My Dictionary" -> null
          - write_only    = false -> null
        }

      + domain {
          + comment = "demo"
          + name    = "testing-deactivation-import.integralist.co.uk"
        }
      - domain {
          - comment = "demo" -> null
          - name    = "testing-deactivation.integralist.co.uk" -> null
        }
    }
```

This makes sense because our Terraform configuration doesn't have a `dictionary` block and so that is going to be marked for deletion from the service. This does give me the opportunity to reuse the dictionary 'container' if I wanted, by putting back in the `dictionary` block, and as long as I kept the name the same (otherwise any change to the dictionary will require it to be deleted and recreated).

Also, I've changed the domain name in the Terraform configuration and so that's caused the domain to need to be modified. 

So if I kept the service name and the domain name the same, and I kept the dictionary resource, then the diff plan would only show changes to the `reuse` and `activate` attributes:

```hcl
Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # fastly_service_vcl.demo will be updated in-place
  ~ resource "fastly_service_vcl" "demo" {
      + activate           = true
      ~ active_version     = 0 -> (known after apply)
      ~ cloned_version     = 1 -> (known after apply)
        id                 = "7TAuMdXDbzzRL9Sp0M8AeS"
        name               = "testing-tf-deactivation"
      + reuse              = true
        # (4 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }
```

Let me know if this implementation of `reuse` would help with your testing flows. It seems like it would because it allows you to reuse a service and its resources (such as the dictionary 'container', which you can then re-populate that dictionary container with new items specific to the new project the service was imported into).

**Comment by JiriKovar** [comment]
Hi @Integralist ,

Yes, that implementation would indeed help us and it is what we need to be able to use terraform destroy. 

Just for the record: One thing I did not mention is that when the Fastly service is actually created for the first time, we immediately clone it do that it has an empty version 1 and when we import the service to the terraform, we run the import with it with @1 version suffix of the service ID = we always start with an empty service to reduce the API calls needed for cleaning the remnants of the previous usage. 

Thank you very much!
