### ISSUE TITLE
Add support for "bypass_local_route_table" or arbitrary backend flags

### ISSUE THREAD

**Issue by StarpTech** [fastly/terraform-provider-fastly#550]
Hi there,

Due to the limitation of C@E we are forced to add `.bypass_local_route_table = true;` to all backends that are chained to a C@E service. This is required because Compute @ Edge isn't deployed on all nodes across all POPs globally. Unfortunately, this flag is not available in this module. It would be great to support this flag or to support an untyped dictionary for feature flags in general e.g.

_Before you can use `bypass_local_route_table` the flag must be enabled on your service or account_

```tf
  dynamic "backend" {
    for_each = var.backends
    content {
      address           = backend.value.origin
      name              = backend.value.origin
      ssl_cert_hostname = backend.value.origin
      override_host     = backend.value.origin
      request_condition = backend.value.origin
      use_ssl           = true
      ssl_check_cert    = true
      port              = 443
      shield = backend.value.shield

      // Solution 1 (preferred)
	  bypass_local_route_table = true
    
	  // Solution 2
	  experimental {
		 .bypass_local_route_table = true
	  }
    }
  }
```

Desired result per backend.

```
backend F_YOUR_HOST {
    ......
   .bypass_local_route_table = true
   
}
```

**Comment by Integralist** [comment]
Hi @StarpTech thanks for opening this issue.

Supporting `.bypass_local_route_table` isn't currently possible as it's not supported within the [Fastly API](https://developer.fastly.com/reference/api/services/backend/).

Even if you were to view the current VCL of your service and copy/paste the backend definition into a VCL Snippet (instead of defining the backend in the Terraform interface using a [`backend` resource](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_compute#nested-schema-for-backend)) then it still wouldn't work because it would also require a pragma to be applied that can only be done internally by Fastly.

I'll open up a ticket internally to track this as a new feature request, and I'll leave this GitHub issue open until such time we have any feedback I can provide.

Thanks.

**Comment by StarpTech** [comment]
Hi @Integralist thanks for the fast response. How should I proceed in that case? We need that flag to roll out our services.

**Comment by Integralist** [comment]
Thanks @StarpTech. 

I would say the quickest way forward for right now would be to reach out to your Fastly account manager (either via the Customer Slack or via support@fastly.com), ping them this GitHub issue if they're not already aware of the issue you're having, and they'll be able to pick this up and get further discussions started.

**Comment by StarpTech** [comment]
Thanks, I'm already in the process :smile:

**Comment by Integralist** [comment]
👋🏻 I'm going to close this issue as I've been informed that as of Sept 2022 (approx) this setting is no longer needed.
