### ISSUE TITLE
In-place TLS private key update

### ISSUE THREAD

**Issue by JindrichPilar** [fastly/terraform-provider-fastly#561]
Hi,

I am trying to update TLS private key and certificate. But documentation doesn't specify how to do it without affecting running services.
**`Terraform plan` says it is going to re-create private key,** which suggests it will impact running services. i.e. there will be downtime for HTTPS connections.

Could you, please, update documentation to specify correct way to update TLS private key and cert and how it will impact running services?

* Terraform version: 1.1.7
* Provider version: 1.1.2

### Terraform Configuration Files

```hcl

# Content of this is changed before running terraform apply
data "azurerm_key_vault_certificate_data" "certificate" {
  key_vault_id = var.tls_kv_id
  name         = var.tls_kv_certificate_name
}

resource "fastly_tls_private_key" "key" {
  name    = "${var.project_name}-wildcard-priv"
  key_pem = data.azurerm_key_vault_certificate_data.certificate.key
}

resource "fastly_tls_certificate" "cert" {
  name             = "${var.project_name}-wildcard-pub"
  certificate_body = data.azurerm_key_vault_certificate_data.certificate.pem
  depends_on       = [fastly_tls_private_key.key]
}

resource "fastly_tls_activation" "cert" {
  for_each = toset(var.domains_to_activate)

  certificate_id = fastly_tls_certificate.cert.id
  domain         = each.value
}

```

### Expected Behavior

Private key is updated in-place.

### Actual Behavior

Terraform re-creates private key resource

```
Terraform will perform the following actions:

  # fastly_tls_certificate.cert will be updated in-place
  ~ resource "fastly_tls_certificate" "cert" {
      ~ certificate_body    = <<-EOT
           __censored__
        EOT
        id                  = "__censored__"
        name                = "__censored__"
        # (8 unchanged attributes hidden)
    }

  # fastly_tls_private_key.key must be replaced
-/+ resource "fastly_tls_private_key" "key" {
      ~ created_at      = "__censored__" -> (known after apply)
      ~ id              = "__censored__" -> (known after apply)
      ~ key_length      = 4096 -> (known after apply)
      ~ key_pem         = (sensitive value) # forces replacement
      ~ key_type        = "RSA" -> (known after apply)
        name            = "__censored__"
      ~ public_key_sha1 = "__censored__" -> (known after apply)
      ~ replace         = false -> (known after apply)
    }
```

### Steps to Reproduce

* Update TLS key+cert input for TF
* Call `terraform apply`

**Comment by Integralist** [comment]
Hi @JindrichPilar thanks for opening this issue.

The provider recreates the whole `fastly_tls_private_key` resource if the `key_pem` or `name` attributes are changed.

The reason behind this was dictated by the `/tls/private_keys` [endpoint](https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/) which doesn't have a `PUT` or `PATCH` method that could be utilised by the TF provider.

So the only way to update a private key is to delete the existing one and upload a new one.

As far as the effect of recreating the key I would suggest reaching out to customer support (support@fastly.com) and directing them to this GitHub issue. Customer support will be able to expedite a conversation with the Fastly TLS team to understand what the expected behaviour would be (and/or if there is anything that might be done within the provider to mitigate any downtime).

Thanks!

**Comment by Integralist** [comment]
There has been no further feedback on this issue, so I'm going to close it. 

Feel free to continue the conversation here if necessary. 
Otherwise I presume the discussion has moved onto the customer support team.

**Comment by Integralist** [comment]
**UPDATE**: I've seen the customer support discussion and I'll be opening an internal ticket to track the work of documenting the process.
