### ISSUE TITLE
fastly_service_dictionary_items cannot handle additions to really large dictionaries

### ISSUE THREAD

**Issue by brionmoss** [fastly/terraform-provider-fastly#571]
### Terraform Version
$ terraform -v
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/fastly/fastly v2.0.0

### Affected Resource(s)
- fastly_service_dictionary_items

### Terraform Configuration Files

I have a very large dictionary -- currently 3403 items.

```
resource "fastly_service_dictionary_items" "redirects" {
  service_id    = var.service_id
  dictionary_id = var.solution_redirects

  items = {
    "/new-test-redirect": "/new-test-redirect-target"
    "/trademark.rl" : "/business-and-contracts/intellectual-property/trademarks/filing/trademark-registration"
    "/rocketwallet" : "/wallet-early-access"
    "/document-checkout-a.rl" : "/document-checkout.rl"
    "/document-checkout-j.rl" : "/document-checkout.rl"
    "/estate-planning/living-trust-center.aspx" : "/family-and-personal/estate-planning/set-up-a-trust"
    "/aboutus.aspx" : "/about-us.rl"
    "/news/article-rocket-lawyer-partnership-with-hiscox-insurance.aspx" : "/press.rl"
     ......MANY MORE LINES HERE
  }
}
```

```
$ fastly dictionary-item list -s 6eAM9EebfbbAYUddsCnA64 --dictionary-id=3NkFExGPt7QMQfnZdl8av0 | wc -l
   23823
$ fastly dictionary-item list -s 6eAM9EebfbbAYUddsCnA64 --dictionary-id=3NkFExGPt7QMQfnZdl8av0 | grep /trademark.rl
	Item Key: /trademark.rl
	Item Key: /intellectual-property/trademark.rl
$ fastly dictionary-item list -s 6eAM9EebfbbAYUddsCnA64 --dictionary-id=3NkFExGPt7QMQfnZdl8av0 | grep test-redirect
$
```

### Debug Output
https://gist.github.com/brionmoss/103898fbfdbafd234d724ea2f13e8e63

### Expected Behavior
I added a new line to top of the list of dictionary items ("/new-test-redirect").

This doesn't get seen as a new redirect to add when doing a terraform plan.

### Actual Behavior
Terraform thinks that there are no changes to apply.

### Steps to Reproduce
1. Create a really really large dictionary (you will have to request Fastly support to waive the default 1000-item limit)
2. After 3400 items are in the dictionary (or thereabouts -- that's the number where things seemed to break down) terraform stops seeing additions to the configured list
3. terraform apply

### Important Factoids
Our Fastly dictionary is unpleasantly large.  Default limit on dictionary size is 1000 and we've topped 3400.

**Comment by Integralist** [comment]
Hi @brionmoss thanks for raising this issue 

Apologies for the delay replying. I held off while a security concern with your debug data was resolved.

So I was able to replicate this issue. I did this by by defining 3000 dictionary items inline into my Terraform configuration file (as per your example uses), which applied without issue. I then added 300 more items inline, but when running a terraform plan, and the state refreshed, Terraform informed me:

```
No changes. Your infrastructure matches the configuration.
```

This is incorrect. We expect there to be a plan diff showing 300 new items to be created.

Now at this point it's worth pointing to Fastly's [Terraform best practices](https://developer.fastly.com/learning/integrations/orchestration/terraform/) resource on the [Fastly Developer Hub](https://developer.fastly.com/). 

One of the recommendations is to [avoiding managing 'data' in Terraform](https://developer.fastly.com/learning/integrations/orchestration/terraform/#configuration-not-data)...

> It's possible to store data in Terraform but it's not advisable to do so because Terraform has a network message size limit that, when exceeded, causes Terraform to fail and be unable to access your Terraform state.
> 
> With this in mind it's preferable to keep your data separate from the Terraform configuration

I mention this because it might be that this 'network message size' limit  is related to the problem you're experiencing.

Effectively Terraform is unable to transport your tfstate, which will be large due to the 3k+ inline dictionary items, via gRPC to its internal 'core' module which handles generating the plan diff.

If I enable trace logs and retry my plan:

```
TF_LOG=TRACE terraform plan
```

I do see there were some errors that appears to suggest a gRPC issue, and might also correlate to the 'network message size' issue:

```
[TRACE] GRPCProvider: Close
[DEBUG] provider.stdio: received EOF, stopping recv loop: 
        err="rpc error: code = Unavailable desc = transport is closing"
[DEBUG] provider: plugin process exited
```

> **NOTE**: I've noticed quite a few open Terraform issues related to this error that are still "open".

I decided to setup a reduced test case where I create a dictionary resource, and configure it with `manage_items  = true`, and then populate the dictionary with 3000 items via the Fastly API. This initial population worked fine, and so I then populated the dictionary with an additional 300 items (again via the Fastly API) and that also succeeded. 

This suggests there shouldn't be any issues with this particular approach with regards to the number of items you're adding.

And as your dictionary items continue to grow I would again recommend moving away from inlining your dictionary items within the Terraform configuration so you can avoid any further potential issues with Terraform itself and its transport size limits.

**Comment by brionmoss** [comment]
Interesting, thank you.

The reason we went to using Terraform with an inlined dictionary was efficiency -- using Terraform we could upload and update the dictionary in just a few minutes, because the provider manages the entire dictionary at once.  The other methods we tried (API calls or CLI tools) took a really long time and we ended up hitting API rate limits because they were trying to process an entry at a time.  I think it would be possible to re-implement the bulk update behavior via API calls but that seemed like a lot of work to go to given that the Terraform provider already has that implemented for us.

The use case here is that we want our content team to be able to manage the list of redirects in github, and have any changes they make automatically update the live dictionary in a controlled way (i.e. automatically go to a test environment, then require approval to promote up from there).  If there's a better way you'd recommend for doing that I'd be happy to try it.

If we do decide to stay with Terraform in order to get the benefit of the bulk update, would it be better to split the data into more dictionaries and just make more lookup() calls from the VCL?

**Comment by Integralist** [comment]
Hi Brion, 

With regards to:

> would it be better to split the data into more dictionaries and just make more lookup() calls from the VCL?

I don't think this would help because although you're sharding your data across separate dictionaries, all the data (now across multiple dictionaries) is still stored/managed via a single tfstate file that Terraform needs to be able to transport to its internal modules for calculating plan/diffs etc.

It is possible to split your Terraform configuration across multiple state files using HashiCorp's [Workspaces feature](https://www.terraform.io/language/state/workspaces), but that isn't going to be a viable solution for your particular problem _unless_ your dictionary data can be sharded via specific categorisation types (e.g. by domain, or environment).

I would also recommend reaching out to support@fastly.com as they might have some additional ideas regarding your comments for how else to handle your requirements.

Hope this information helps.

**Comment by Integralist** [comment]
I'm going to close this issue as there has been no further discussion. 

Feel free to continue the conversation or to re-open, if there is a bug identified in the Fastly provider logic itself.

Thanks.
