### ISSUE TITLE
Fastly_service_compute requires a "package" block

### ISSUE THREAD

**Issue by yannh** [fastly/terraform-provider-fastly#638]
Hello! 

The "fastly_service_compute" resource has a mandatory "package" block - for my use case, I would like to create & manage the Fastly service using Terraform, but the actual code through a separate CI process (possibly using the Fastly Github Action). I suspect I might be able to initialize the compute service using this provider with a "hello-world" wasm file, and then use lifecycle ignores - but it would be nicer if this resource did not require a package block. I believe the API does not have this requirement, so this should be solvable in the provider directly?

What do you think?

Many thanks!

**Comment by Integralist** [comment]
Hi @yannh 

Thanks for reaching out with this question.

The issue that I see with making the `package` block optional is that Terraform is no longer responsible for the entire life-cycle of the 'service' resource. This means the provider will only be able to track the last known 'inactive' service version (as you can't activate a compute service _without_ a package uploaded to it, and so if we did make `package` optional you'd also have to set `activate=false` on the service resource to prevent API errors being returned) and so manually uploading a package to the service outside of Terraform means the provider won't know about it and will ignore the manually activated version. 

Terraform is designed to manage the full life-cycle of a 'resource' and unfortunately Fastly's data model (e.g. a service contains domains, backends, package etc) makes that relationship much more complicated.

It would be better if each block (e.g. domain, backend, package etc) were its own 'resource' but again, due to Fastly's service model design that's not possible for us to implement within the Terraform provider at this time. 

Fastly is aware of these limitations and is actively investigating options to resolve them but I don't foresee us being able to make `package` optional any time soon. With that in mind I'm going to close this issue but do feel free to continue the conversation if you have any more thoughts/feedback.

Thanks!

**Comment by yannh** [comment]
Hi @Integralist , thank you for the feedback, yes - I was not aware of the logical inter-dependencies between blocks. You are right that it would mean that terraform is not responsible for the entire lifecycle of the resource anymore - I might be ok with the tradeoff, but that might be an edge case. I shall be able to workaround this with lifecycle ignores. Thanks for the quick and thorough response :pray: !
