### ISSUE TITLE
fastly_tls_subscription doesn't appear to support updates with custom tls_configuration

### ISSUE THREAD

**Issue by rayterrill** [fastly/terraform-provider-fastly#669]
### Terraform Version
```
v1.3.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_tls_subscription

### Terraform Configuration Files
```hcl
data "fastly_tls_configuration" "config" {
  name = var.fastly_tls_configuration
}

resource "fastly_tls_subscription" "tlssub" {
  domains               = [for domain in fastly_service_vcl.service[0].domain : domain.name]
  certificate_authority = "lets-encrypt"
  configuration_id      = data.fastly_tls_configuration.config[0].id

  force_update          = true
  force_destroy         = true

  common_name           = local.fqdn
}
```

### Expected Behavior
What should have happened?

We should be able to modify tls_subscription resources with custom tls_configurations.

### Actual Behavior
What actually happened?

400 on the update.
```
 Error: 400 - Bad Request:
│
│     Title:  Bad request
│     Detail: Must provide TLS configuration relationship
│
│   with fastly_tls_subscription.tlssub[0],
│   on fastly.tf line 153, in resource "fastly_tls_subscription" "tlssub":
│  153: resource "fastly_tls_subscription" "tlssub" {
```

Looking at the go code here, it looks like there might again be an implicit dependency on the default tls configuration option?

And it looks like the existing code to build up the update doesn't account for the configuration id correctly: [terraform-provider-fastly/fastly/resource_fastly_tls_subscription.go](https://github.com/fastly/terraform-provider-fastly/blob/e0c80d39060082271f382965d21d341e1affaeb0/fastly/resource_fastly_tls_subscription.go#L328-L331)

it only adds that piece in if there's a change:
[terraform-provider-fastly/fastly/resource_fastly_tls_subscription.go](https://github.com/fastly/terraform-provider-fastly/blob/e0c80d39060082271f382965d21d341e1affaeb0/fastly/resource_fastly_tls_subscription.go#L343-L345)

It looks like this is a PATCH so I'm surprised that's erroring out, but it does appear to be doing so.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. build a tls_subscription using a customer tls_configuration
2. attempt to update that tls_subscription without changing the tls_configuration (adding or removing a domain is what i was doing)

**Comment by Integralist** [comment]
Hi @rayterrill 

I've read through your issue report and I've also had a look at both the 'update' function code in the provider and the go-fastly API client code, and I agree it does look like there might be an issue with the Terraform provider implementation.

## Problem

**So let me first repeat back what I think you're trying to do and why it's breaking (just so we can both be sure I've understood your report)...**

- You want to add/remove a domain on your TLS Subscription without changing the existing TLS Configuration you're using. 
- You have a specific TLS configuration object you are already using with the TLS Subscription, and this is why you have `fastly_tls_configuration` configured using the `id` attribute set to a specific TLS Configuration object ID (rather than having it trying to filter a list of configuration objects down to a single object, as per the documented examples we provide).
- The provider's `resourceFastlyTLSSubscriptionUpdate` function uses Terraform's `HasChange(<attribute>)` method to detect any changes to the specified HCL attribute, and if there was a change to the attribute, then [the input to the go-fastly API client would have the corresponding input field set](https://github.com/fastly/terraform-provider-fastly/blob/main/fastly/resource_fastly_tls_subscription.go#L333-L345).
- Looking at the go-fastly API client's input struct `UpdateTLSSubscriptionInput` [the code comments](https://github.com/fastly/terraform-provider-fastly/blob/main/vendor/github.com/fastly/go-fastly/v7/fastly/tls_subscription.go#L239-L244) seem to suggest that each of those fields (`CommonName`, `Configuration` and `Domains`) must be set even if it's just the same values as before.
- At the moment only the `Domains` field is being set (as per your report: you've either added/removed a domain in your HCL configuration) but because the `CommonName` and `Configuration` fields aren't being set (as there are no changes in your HCL for those), it is causing the API to error with (due to the missing `Configuration` field specifically) "Must provide TLS configuration relationship".

## Solution

We should update the Terraform provider's `resourceFastlyTLSSubscriptionUpdate` function to remove the conditional `d.HasChange(<attribute>)` blocks. 

This would cause the existing values for the `common_name` and `configuration_id` attributes to be passed to the go-fastly API client. 

Setting these fields is OK because the attributes should have valid values to use as they would have had their values computed straight after the original 'create' operation had completed (and because at the end of the 'create' step the provider calls the API to get the latest subscription data back for the `common_name` and `configuration_id` attributes and then sets them into the Terraform state).

I'll check in with the Fastly TLS team just to be sure there aren't any problems here that I'm not seeing, but I think this is what we need to do. I'll update this issue once I've had some feedback from the TLS team.

Thanks!

**Comment by rayterrill** [comment]
Looks correct to me @Integralist - TY! We also opened a case with support on this.

**Comment by Integralist** [comment]
Hi @rayterrill 

Are you able to email me (integralist@fastly.com) with the support ticket number you have and your customer number, that way when talking to the TLS team I can point them at your ticket. Thanks!

Also, they mentioned something interesting which was...

> Passing no "tls_configuration" relationship should be fine.

What he said actually conflicts which what you're seeing as far as the API response: "Must provide TLS configuration relationship".

So are you able to copy/paste the actual API calls being made so we can double-check the Terraform provider is making the expected API calls. Again, feel free to email that data directly to me if you don't want to share it publicly/redacted.

Thanks!

**Comment by rayterrill** [comment]
Yep, will do. Just ran it in debug mode and got the api call. Confirmed the API call fails in postman as well.
