### ISSUE TITLE
rate_limiter: uri dictionary must exist bug

### ISSUE THREAD

**Issue by rayzorinc** [fastly/terraform-provider-fastly#724]
### Terraform Version

`1.0.11`

fastly provider version:
`v5.2.0`

### Affected Fastly Terraform Resource(s)
`fastly_service_vcl`:
   * `dictionary`
   * `rate_limiter`

### Terraform Configuration Files

```hcl

resource "fastly_service_vcl" "service" {
  name = "test"
 ....
  dictionary {
      name          = "rate_limit_path"
      write_only    = false
  }
  rate_limiter {
     action               = "response"
     client_key           = "client.ip,req.http.User-Agent"
     http_methods         = "GET,PUT,TRACE,POST,HEAD,DELETE,PATCH,OPTIONS"
     name                 = "rate limit"
     penalty_box_duration = 2
     rps_limit            = 100
     uri_dictionary_name  = "rate_limit_path"
     window_size          = 60

     response {
          content      = <<-EOT
                   <html>
                   	<head>
                   		<title>Too Many Requests</title>
                   	</head>
                   	<body>
                   		<p>Too Many Requests</p>
                   	</body>
                   </html>
          EOT
          content_type = "text/html"
          status       = 429
     }
  }
}

```

### Expected Behavior
I expected it should create the dictionary and successfully assigned the `uri_dictionary_name` params in the `rate_limiter` block.

### Actual Behavior
Gave an error that the dictionary doesn't exist yet, which is kinda true, cause I wanted the tf to create it , and then assign that dictionary to the rate limit.

TF response below:
```
╷
│ Error: 400 - Bad Request:
│
│     Title:  Bad request
│     Detail: Uri dictionary name must exist
│     RateLimitRemaining: 996
│     RateLimitReset:     1688576400
│
│   with module.test_service.fastly_service_vcl.service,
│   on main.tf line 2, in resource "fastly_service_vcl" "service":
```

### Steps to Reproduce
Create a `fastly_service_vcl` resource with a new dictionary and rate_limiter define similar to above configuration

1. `terraform apply`

## Debug Output

```
2023-07-05T12:27:49.688-0400 [DEBUG] provider.terraform-provider-fastly_v5.2.0: Creating clone of version (109) for updates: timestamp=2023-07-05T12:27:49.688-0400
2023-07-05T12:27:50.024-0400 [DEBUG] provider.terraform-provider-fastly_v5.2.0: Sleeping 7 seconds to allow Fastly Version to be available: timestamp=2023-07-05T12:27:50.024-0400
2023-07-05T12:27:57.109-0400 [DEBUG] provider.terraform-provider-fastly_v5.2.0: Update Rate Limiter: fastly.UpdateERLInput{Action:(*fastly.ERLAction)(nil), ClientKey:(*[]string)(nil), ERLID:"XXXXXXX", FeatureRevision:(*int)(nil), HTTPMethods:(*[]string)(0xc000896180), LoggerType:(*fastly.ERLLogger)(nil), Name:(*string)(nil), PenaltyBoxDuration:(*int)(nil), Response:(*fastly.ERLResponseType)(nil), ResponseObjectName:(*string)(nil), RpsLimit:(*int)(nil), URIDictionaryName:(*string)(0xc00093e7f0), WindowSize:(*fastly.ERLWindowSize)(nil)}: timestamp=2023-07-05T12:27:57.109-0400
2023-07-05T12:27:57.239-0400 [TRACE] provider.terraform-provider-fastly_v5.2.0: Called downstream: @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:848 tf_provider_addr=provider tf_rpc=ApplyResourceChange @module=sdk.helper_schema tf_req_id=92ba704e-d3eb-9d87-f5b3-ac00d69af075 tf_resource_type=fastly_service_vcl timestamp=2023-07-05T12:27:57.239-0400

```
The debug output looks like it tried to update the rate limiter first before creating the dictionary.

The rate limiter should be updated after the dictionary has been created.

**Comment by Integralist** [comment]
👋🏻 

Thanks for opening this issue. 

Unfortunately, the only solution here is going to be executing a two-step apply.

1. Apply the dictionary creation.
2. Apply the rate_limiter creation.

The reason this is a tricky issue is that you can't use the `depends_on` meta-argument in Terraform to couple the two 'blocks' (`depends_on` only works between resources/data-sources).

Similarly, you can't reference any of the read-only attributes of one 'block' from a separate 'block' like you can when referencing a resource's read-only output fields (which is a common way for Terraform to create a dependency tree). So even if we exposed a 'name' read-only attribute on the `dictionary` block, you couldn't reference it from within the `rate_limiter` block to cause an implicit dependency coupling.

We also can't change the `rate_limiter` block to be a separate resource, because we need it to exist _inside_ the `fastly_service_vcl` resource so it has access to the Service ID/Service Version that's being tracked, and more importantly it needs to have access to a new 'draft' (i.e. inactive) service version. If we made it a separate resource, then yes we could pass in a Service ID and Service Version, but the service version would already have been 'activated' and so the CREATE operation for the rate limiter would fail as you can only create a rate limiter within an inactive service version. 

Yes, the rate limiter (as a separate resource) could make an API call to clone the service version, but then there would be a version drift between the service version that the `fastly_service_vcl` resource was able to track and the version that the rate_limiter resource created as a side-effect (due to data isolation in the Terraform design we can't then inform the `fastly_service_vcl` resource of a change in version to track). There are a bunch of similar/related complications with having rate_limiter as a separate resource** which makes this a non-option.

> ** This is something I've spent a lot of time investigating recently as part of a larger rewrite of the Terraform provider. We've realised Fastly's data model (i.e. many components having to exist _within_ a 'service') makes it tricky to step away from the interface design we've historically supported.

Because of this I'm going to close this issue but feel free to continue the conversation if you have any other questions/comments

Thanks!

**Comment by rayzorinc** [comment]
>** This is something I've spent a lot of time investigating recently as part of a larger rewrite of the Terraform provider. We've realised Fastly's data model (i.e. many components having to exist within a 'service') makes it tricky to step away from the interface design we've historically supported.

👍🏼 to have the fastly service resource break apart. it will make things easier for us to have a base module that can support many of our services that require slightly different fastly configuration.  is there a public timeline when that will happen?

**Comment by Integralist** [comment]
> 👍🏼 to have the fastly service resource break apart. it will make things easier for us to have a base module that can support many of our services that require slightly different fastly configuration. is there a public timeline when that will happen?

Unfortunately, this isn't going to be possible to have the different Fastly APIs (e.g. backends, domains, etc) separate from the `fastly_service_*` resources because of Terraform's data isolation design.

I previously investigated how we might do this and found that because of Fastly's data model (e.g. it needs these different components like backends, domains etc to be created _within_ an inactive service version) we can't support a design where everything is a separate resource (which is how Terraform expects things to behave, e.g. an API endpoint should map 1:1 with a resource where our `fastly_service_*` resources are a 1:many mapping, one resource to _many_ different APIs).

**Comment by lemkepf** [comment]
I ran into this same issue today... and wasted hours trying to figure out what the issue was. Can you put some kind of documentation on the terraform doc site so we can understand this BEFORE wasting hours and hours. 

Also - Why can't you just create the service without the rate limiter first, then add the rate limiter after? Just change the order. Seems like a major design oversight to not support that.
