### ISSUE TITLE
Fastly provider 0.4 - when applying VCL code that references resources like tables or snippets already included on the service - throws an error

### ISSUE THREAD

**Issue by javapapo** [fastly/terraform-provider-fastly#98]
Hi there,

### Terraform Provider  Version
0.4 

### Behavior 
We have a Fastly Service, which is `maintained` through terraform, meaning properties and vcl are uploaded with terraform and the terraform fastly provider.

On this fastly service, through the API we have added, a dynamic snippet, which contains a table (dictionary)

Example
--------

```vcl
# Snippet search_redirects : 100
 # --- Fastly Synchronizer - START # --- Fastly Synchronizer - UPDATE DATE:2018-10-03T11:50:00.071
  table search_redirects { "santa+pod+raceway": "/santapod","elton john":}
```

On our terraformed Fastly configuration - we do include either on the `Main.vcl` or other `vcl` files which are added to the service  - code that references..this table!. Since the snippet is versioned independently from the fastly service it is always available.

For example we added ...the snippet on version 40 of a service. Then we run our terraform fastly pipeline which increments the service to version 41 and includes code on the `Main.vcl` like this

```vcl

  # Search redirects based on the fastly dictionaryt and not on TMOL proxies
  # /search&user_input=mel+c&q=Melanie+C
  if(req.url.path ~ "^/search"){
      declare local var.qParam STRING;
      declare local var.qParamLink STRING;
      set var.qParam = subfield(req.url.qs, "q", "&");
      set var.qParam = urldecode(var.qParam);
      set var.qParamLink = table.lookup(search_redirects, std.tolower(var.qParam),"NOT_FOUND");

      }
    }
```

So the uploaded VCL in this case is the `Main.vcl` references...and specifically the line

```
      set var.qParamLink = table.lookup(search_redirects, std.tolower(var.qParam),"NOT_FOUND");
```

Assumes that there is on the service level this table! 

ALL THE ABOVE WERE WORKING fine with fastly provider 0.3 .

Now 17 hours after re-running the same pipeline .....on the above conditions with provider. 0.4 during the apply phase, when the above already established VCL is applied - Fastly reports an error 
Like the followig

```* fastly_service_v1.tmolauprod: 1 error(s) occurred:

* fastly_service_v1.tmolauprod: [ERR] Invalid configuration for Fastly Service (xxxx): Undefined `table search_redirects`
at: (input Line 271 Pos 39)
    set var.qParamLink = table.lookup(search_redirects, std.tolower(var.qParam),"NOT_FOUND");
```

It seems when the VCL that references the table (from the snippet) it kind of ends up on a compile error - like the table is not there any more.

When you apply the same thing ...using provider 0.3 everything works.

```
provider "fastly" {
 version = "0.3"
}
```

**Comment by hynd** [comment]
After poking about a bit, i don't think this is a bug (at least one specific to snippets - keep reading...).

This provider assumes that for pretty much anything it's cognizant of, it wholly manages for a given service.  If something has changed in the config (ie; via a method other than Terraform), Terraform will delete and create it again (via POST API calls, ie; it never update/PUT's anything).  So, if something was added via a method other than Terraform, Terraform will delete it.

If you're adding a VCL `snippet` out-of-band and Terraform doesn't know about it, it'll delete it.  It'll do the same for anything else it knows about - `backend`'s, `condition`'s, `healthcheck`'s etc.  It just happens that in 0.4.0, the provider became "aware" of snippets and now tries to manage them in the same way.

@lanej / @thommahoney - is that accurate? How would you prefer to handle this?  At the moment, dynamic snippets aren't supported which is why they've been added behind Terraform's back.

I have a temporary tweak i can PR to make the provider ignore dynamic snippets until it can support it? (which at first glace seems non-trivial).
The above behaviour would remain on "regular" snippets, but since they're versioned alongside the entire service config, i'd assume there were fewer people adding/changing them via API calls...

**Comment by javapapo** [comment]
>> if you're adding a VCL snippet out-of-band and Terraform doesn't know about it, it'll delete it

It is very important -the above...is a breaking change for all the users like `me` that have been using the provider for more than a year. We were relying on this convention. Dynamic resources since are not versioned along with the Service, are assumed to be there...when the terraformed resources were updated. If they were not there thats the responsibility of the maintainer - us.

What I am trying to say is that - it should not try to delete a snippet that was added through the API... un less of course proper support for snippets or edge dictionaries is added + a way to migrate existing services like the one in the example.

**Comment by jare19** [comment]
@hynd could you please PR this fix, https://github.com/hynd/terraform-provider-fastly/commit/9bfd203b3be5989b70e2ebbe5f677248d3081ed9 ,  we use dynamic snippets and the current version of this provider destroys the dynamic (versionless) snippet that we modify via API calls, thus defeating the purpose of dynamic (versionless) snippets.
